# Generated by Django 3.1.3 on 2020-11-03 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], null=True, size=None)),
                ('stock_weights', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(verbose_name=0), default=[], null=True, size=None)),
                ('stock_exchanges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], null=True, size=None)),
                ('telegram_subscribers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], null=True, size=None)),
            ],
        ),
    ]
