# Generated by Django 3.1.3 on 2020-11-03 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 19, 39, 5, 197936, tzinfo=utc)),
        ),
    ]
