# Generated by Django 3.1.3 on 2020-11-03 20:05

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 20, 5, 20, 921042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stock_exchanges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], null=True, size=None),
        ),
    ]
